{{- if eq (.Values.global.monitoring.enabled | toString) "true" }}
{{- include "service-chart.prometheusrule" (list . "kcm.prometheusrule") -}}
{{- end -}}
{{- define "kcm.prometheusrule" -}}
{{- if gt (len .Values.rules) 0}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "service.fullname" . }}
spec:
  groups:
    - name: {{ include "service.fullname" . }}-srv-alerts
      rules:
        {{- .Values.rules | toYaml | nindent 8 }}
{{- end }}
{{- end -}}