name: Helm Publish
on:
  workflow_run:
    workflows: ["Publish Docker"]
    types: [completed]
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v1
      - name: Add Helm repos
        run: "helm repo add kaa https://museum.kaaiot.net"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: charts/${{ github.event.repository.name }}
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
