name: Helm Publish
on:
  workflow_run:
    workflows: ["Publish Docker"]
    types: [completed]
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - uses: azure/setup-helm@v1
      - name: Add Helm repos
        run: "helm repo add kaa https://museum.kaaiot.net"
      - name: Lint chart
        run: "helm lint charts/${{github.event.repository.name}}"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
